config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :trips
  resources :reviews

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/home/sad', to: 'home#sad'
  get '/dashboard/my_trips', to: 'users#show_my_trips', as: 'my_trips'
  get '/trips/:id/reviews', to: 'trips#show_reviews', as: 'show_trip_reviews'
  get '/home/search_trips', to:'trips#show_search_trips', as: 'show_search_trips'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :trip
	belongs_to :user
end

app/models/trip.rb
class Trip < ApplicationRecord
	has_many :reviews
	belongs_to :user

	validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@trips = Trip.all
	end
	def sad
		render "home/sad", :layout => false
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	#only show reviews pertaining to a trip passed into params
	def index
	end

	#show review for a single trip?
	def show
		#no need b/c we just show all at once
	end

	# push to database or something
	def create
		@review = Review.new(review_params)
		# ensure that there is a description
		if @review.description.blank?
			flash[:error] = 'Your review must have a description!'
			redirect_to new_review_path
		else
			# continue with rest of saving
			@review.user = current_user #.id?
			if @review.save
				redirect_to trip_path(id: @review.trip.id)
			else
				flash[:error] = @review.errors.full_messages.to_sentence
				redirect_to new_review_path
			end
		end
	end

	# route to create review form
	def new
		@review = Review.new
		@trip_id = params[:trip_id]
		# @review.trip_id = @trip_id
	end

	private 
	def review_params
    	params.require(:review).permit(:title, :rating, :description, :trip_id)
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	#show page for a single trip
	def show
		@trip = Trip.find(params[:id])
		@reviews = Review.where(:trip_id => @trip.id)
	end

	def show_search_trips
		puts params
		@search_input = params[:searchbarn]
		@results = Trip.where(:start_location => @search_input)
	end

	# push to database or something
	def create
		#puts params
		@new_trip = Trip.new(new_trip_params)
		# ensure that at least one activity is filled
		if @new_trip.morning.blank? && 
			@new_trip.breakfast.blank? &&
			@new_trip.noon.blank? &&
			@new_trip.lunch.blank? &&
			@new_trip.afternoon.blank? &&
			@new_trip.dinner.blank? &&
			@new_trip.evening.blank? &&
			@new_trip.night.blank?

			flash[:error] = 'Your trip must have at least one activity'
			redirect_to new_trip_path
		else
			# continue with rest of saving
			if !@new_trip.morning.blank?
				@start_location = @new_trip.morning
			elsif !@new_trip.breakfast.blank?
				@start_location = @new_trip.breakfast
			elsif !@new_trip.noon.blank?
				@start_location = @new_trip.noon
			elsif !@new_trip.lunch.blank?
				@start_location = @new_trip.lunch
			elsif !@new_trip.afternoon.blank?
				@start_location = @new_trip.afternoon
			elsif !@new_trip.dinner.blank?
				@start_location = @new_trip.dinner
			elsif !@new_trip.evening.blank?	
				@start_location = @new_trip.evening
			elsif !@new_trip.night.blank?	
				@start_location = @new_trip.night
			end

			@new_trip.start_location = @start_location
			@new_trip.user = current_user
			if @new_trip.save
				redirect_to root_path
			else
				flash[:error] = @new_trip.errors.full_messages.to_sentence
				redirect_to new_trip_path
			end
		end
	end

	# route to create trip form
	def new
		@new_trip = Trip.new
	end

	def show_reviews
		puts params
		@trip = Trip.find(params[:id])
		@reviews = Review.where(:trip_id => @trip.id)
	end

	private 
	def new_trip_params
    	params.require(:trip).permit(:name,
    		:morning, :breakfast, :noon, :lunch, :afternoon, :dinner, :evening, :night)

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@reviews = Review.where(:user_id => current_user.id)
	end

	def show_my_trips
		@trips = Trip.where(:user_id => current_user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Welcome to TripPlanner</h3>

<!-- <p><%= link_to 'Users', users_path %></p> -->


 <!-- <iframe height = "400px" width="100%" frameborder = "0" scrolling = "no" src="home/sad" allowfullscreen></iframe> -->
 <% if @trips %>
	<% @trips.each do |t| %>
			<h3><%= link_to t.name, trip_path(id: t.id), :method => :get %> </h3></br>
			<!-- add other stuff from api call -->
	<%end%>
<%else %>
	<p>You got no trips boyy</p>
<%end%>


<% if current_user %>
	<%= button_to "Create trip", new_trip_path, :class => "button small", :method => :get %> 
<% end %>

app/views/home/mapsTest.html.erb
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/home/sad.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaceID Geocoder</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      .controls {
        background-color: #fff;
        border-radius: 2px;
        border: 1px solid transparent;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        box-sizing: border-box;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        height: 29px;
        margin-left: 17px;
        margin-top: 10px;
        outline: none;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
      }

      .controls:focus {
        border-color: #4d90fe;
      }
      .title {
        font-weight: bold;
      }
      #infowindow-content {
        display: none;
      }
      #map #infowindow-content {
        display: inline;
      }

    </style>
  </head>
  <body>
    <%= text_field_tag :searchbarn %>
    <%= button_to "Search", show_search_trips_path, :class => "button small", :method => :get %> 

    <div id="map"></div>
    <div id="infowindow-content">
      <span id="place-name"  class="title"></span><br>
      Place ID <span id="place-id"></span><br>
      <span id="place-address"></span>
    </div>

    <script>
      // This sample uses the Place Autocomplete widget requesting only a place
      // ID to allow the user to search for and locate a place. The sample
      // then reverse geocodes the place ID and displays an info window
      // containing the place ID and other information about the place that the
      // user has selected.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -33.8688, lng: 151.2195},
          zoom: 13
        });

        var input = document.getElementById('searchbarn');

        var autocomplete = new google.maps.places.Autocomplete(
            input, {placeIdOnly: true});
        autocomplete.bindTo('bounds', map);

        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        var infowindow = new google.maps.InfoWindow();
        var infowindowContent = document.getElementById('infowindow-content');
        infowindow.setContent(infowindowContent);
        var geocoder = new google.maps.Geocoder;
        var marker = new google.maps.Marker({
          map: map
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          var place = autocomplete.getPlace();

          if (!place.place_id) {
            return;
          }
          geocoder.geocode({'placeId': place.place_id}, function(results, status) {

            if (status !== 'OK') {
              window.alert('Geocoder failed due to: ' + status);
              return;
            }
            map.setZoom(11);
            map.setCenter(results[0].geometry.location);
            // Set the position of the marker using the place ID and location.
            marker.setPlace({
              placeId: place.place_id,
              location: results[0].geometry.location
            });
            marker.setVisible(true);
            infowindowContent.children['place-name'].textContent = place.name;
            infowindowContent.children['place-id'].textContent = place.place_id;
            infowindowContent.children['place-address'].textContent =
                results[0].formatted_address;
            infowindow.open(map, marker);
          });
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initMap"
        async defer></script>
  </body>
</html>

app/views/home/show_search_trips.html.erb
<% if @results %>
	<% @results.each do |t| %>
		<% if current_user.id == t.user_id %>
			<h3><%= link_to t.name, trip_path(id: t.id), :method => :get %> </h3></br>
			<!-- add other stuff from api call -->
		<%end%>
	<%end%>
<%else %>
	<p>You got no results boyy</p>
<%end%>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'TripPlanner Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li><%= link_to 'My Profile', user_path(id: current_user.id) %></li>
  <li><%= link_to 'Edit Your Profile', edit_user_registration_path %></li>
  <li><%= link_to 'Log Out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to 'Join TripPlanner', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TripPlannerApp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PokePortal" %>">
   
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/reviews/new.html.erb
<h3>Create a review</h3>

<%= simple_form_for @review do |f| %>
  <%= f.input :title, label: "Title" %>
  <%= f.input :rating, label: "Rating", collection: 1..5, selected: 5 %>
  <%= f.input :description, label: "Description", :as => :text %>
  <%= f.hidden_field :trip_id, :value => @trip_id %>

<%= button_to "Save review", reviews_path, :class => "button small", :method => :post %> 
<% end %>

app/views/trips/new.html.erb
<h3>Create a new Trip</h3>

<%= simple_form_for @new_trip do |f| %>
  <%= f.input :name, label: "Trip name" %>
  <%= f.input :morning, label: "Morning activity" %>
  <%= f.input :breakfast, label: "Breakfast" %>
  <%= f.input :noon, label: "Noon activity" %>
  <%= f.input :lunch, label: "Lunch" %>
  <%= f.input :afternoon, label: "Afternoon activity" %>
  <%= f.input :dinner, label: "Dinner" %>
  <%= f.input :evening, label: "Evening activity" %>
  <%= f.input :night, label: "Night activity" %>

<%= button_to "Save trip", trips_path, :class => "button small", :method => :post %> 
<% end %>


       <script>
      // This sample uses the Place Autocomplete widget requesting only a place
      // ID to allow the user to search for and locate a place. The sample
      // then reverse geocodes the place ID and displays an info window
      // containing the place ID and other information about the place that the
      // user has selected.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function init() {
	      var swag = ['trip_morning', 'trip_breakfast', 'trip_noon', 'trip_lunch', 'trip_afternoon', 'trip_dinner', 'trip_evening', 'trip_night'];
	      for (i = 0; i < swag.length; i++) {
	      	var input = document.getElementById(swag[i]);
	      	autocomplete = new google.maps.places.Autocomplete(input);
	      	var place = autocomplete.getPlace();
	      }
	  }
      // var input = document.getElementById('trip_morning');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();

      // var input2 = document.getElementById('trip_breakfast');
      // var autocomplete2 = new google.maps.places.Autocomplete(input2);
      // var place2 = autocomplete.getPlace();
      // }
      // function initBreakfast() {
      // var input = document.getElementById('trip_breakfast');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
      // function initNoon() {
      // var input = document.getElementById('trip_noon');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
      // function initLunch() {
      // var input = document.getElementById('trip_lunch');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
      // function initAfternoon() {
      // var input = document.getElementById('trip_afternoon');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
      // function initDinner() {
      // var input = document.getElementById('trip_dinner');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
      // function initEvening() {
      // var input = document.getElementById('trip_evening');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
      // function initNight() {
      // var input = document.getElementById('trip_night');
      // var autocomplete = new google.maps.places.Autocomplete(input);
      // var place = autocomplete.getPlace();
      // }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=init"
        async defer></script>
<!--             <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initBreakfast"
        async defer></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initNoon"
        async defer></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initLunch"
        async defer></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initAfternoon"
        async defer></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initDinner"
        async defer></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initEvening"
        async defer></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3Jm_HKgLW1-kpvhnwp3NryCXrzDBdJRQ&libraries=places&callback=initNight"
        async defer></script>
 -->

app/views/trips/show.html.erb
<h2><%= @trip.name if @trip.name %></h2>

<% if current_user && current_user.id != @trip.user_id%>
	<% if Review.where(:id => current_user.id)%>
		<%= link_to "Add review", {:controller => 'reviews', :action => 'new', :trip_id => @trip.id}, :class => "button small", :method => :get %>
	<%else%>
		<%= link_to "Edit review", {:controller => 'reviews', :action => 'edit', :trip_id => @trip.id}, :class => "button small", :method => :get %>
	<%end%>
<%end%>

<h3>Your day</h3>
<!-- {:controller => 'reviews', :action => 'new', :trip_id => @trip.id} #These will be API calls to show information, render a separate layout -->
<p>Morning: <%= @trip.morning %></p>
<p>Breakfast: <%= @trip.breakfast %></p>
<p>Noon: <%= @trip.noon %></p>
<p>Lunch: <%= @trip.lunch %></p>
<p>Afternoon: <%= @trip.afternoon %></p>
<p>Dinner: <%= @trip.dinner %></p>
<p>Evening: <%= @trip.evening %></p>
<p>Night: <%= @trip.night %></p>

<h3><%= link_to 'Reviews', show_trip_reviews_path(:id => @trip.id), :method => :get %> </h3>

app/views/trips/show_reviews.html.erb
<h1>Reviews for <%= @trip.name %></h1>
<% if @reviews %>
	<% @reviews.each do |r| %>
		<% if @trip.id == r.trip_id %>
			<%if r.title%>
				<h3><%=r.title%></h3>
			<%else%>
				<h3>No title</h3>
			<%end%>
			<p>User: <%=User.find(r.user_id).email%></p>
			<p>Rating: <%=r.rating%></p>
			<p>Description: <%=r.description%></p></br>
		<%end%>
	<%end%>
<%else %>
	<p>This trip has no reviews boyy</p>
<%end%>

app/views/trips/show_search_trips.html.erb
<% if @results %>
	<% @results.each do |t| %>
		<% if current_user.id == t.user_id %>
			<h3><%= link_to t.name, trip_path(id: t.id), :method => :get %> </h3></br>
			<!-- add other stuff from api call -->
		<%end%>
	<%end%>
<%else %>
	<p>You got no results boyy</p>
<%end%>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

<h3>Your reviews</h3>

app/views/users/show_my_trips.html.erb
<h1>Your Trips</h1>
<% if @trips %>
	<% @trips.each do |t| %>
		<% if current_user.id == t.user_id %>
			<h3><%= link_to t.name, trip_path(id: t.id), :method => :get %> </h3></br>
			<!-- add other stuff from api call -->
		<%end%>
	<%end%>
<%else %>
	<p>You got no trips boyy</p>
<%end%>